SELECT
    PAPF.PERSON_NUMBER AS EMPLOYEE_CODE ,
    PPNF.FIRST_NAME ,
    PPNF.FULL_NAME ,
    TO_CHAR(PP.DATE_OF_BIRTH,'DD-MONTH-YYYY') DATE_OF_BIRTH ,
    PEA.EMAIL_ADDRESS ,
    TO_CHAR(PPS.DATE_START,'DD-MONTH-YYYY') DATE_OF_JOINING ,
    HOUFT.NAME DEPARTMENT ,
    CASE 
        WHEN TO_CHAR(PP.DATE_OF_BIRTH, 'MM-DD') = TO_CHAR(SYSDATE, 'MM-DD') THEN 'Birthday'
        WHEN TO_CHAR(PPS.DATE_START, 'MM-DD') = TO_CHAR(SYSDATE, 'MM-DD') THEN 
        CASE 
            WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, PPS.DATE_START) / 12) = 1 THEN '1st Work Anniversary'
            WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, PPS.DATE_START) / 12) = 2 THEN '2nd Work Anniversary'
            WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, PPS.DATE_START) / 12) = 3 THEN '3rd Work Anniversary'
            ELSE TO_CHAR(FLOOR(MONTHS_BETWEEN(SYSDATE, PPS.DATE_START) / 12)) || 'th Work Anniversary'
        END
        ELSE NULL
    END AS INFO
FROM
    PER_ALL_PEOPLE_F PAPF ,
    PER_PERSON_NAMES_F PPNF ,
    PER_PERSONS PP ,
    PER_EMAIL_ADDRESSES PEA ,
    PER_PERIODS_OF_SERVICE PPS ,
    PER_ALL_ASSIGNMENTS_M PAAM ,
    HR_ORGANIZATION_UNITS_F_TL HOUFT
WHERE
    1=1
    AND PAPF.PERSON_ID = PPNF.PERSON_ID
    AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
    AND PPNF.NAME_TYPE='GLOBAL'
    AND PAPF.PERSON_ID = PP.PERSON_ID
    AND PAPF.PERSON_ID = PEA.PERSON_ID
    AND PEA.EMAIL_TYPE = 'W1'
    AND PAPF.PERSON_ID = PAAM.PERSON_ID
    AND PAAM.ASSIGNMENT_TYPE = 'E'
    AND PAAM.PRIMARY_FLAG = 'Y'
    AND PAAM.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
    AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
    AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
    AND PAAM.PERIOD_OF_SERVICE_ID = PPS.PERIOD_OF_SERVICE_ID
    AND PAAM.ORGANIZATION_ID = HOUFT.ORGANIZATION_ID(+)
    AND TRUNC(SYSDATE) BETWEEN HOUFT.EFFECTIVE_START_DATE AND HOUFT.EFFECTIVE_END_DATE
    AND HOUFT.LANGUAGE = 'US'
    AND (
           TO_CHAR(PP.DATE_OF_BIRTH, 'MM-DD') = TO_CHAR(SYSDATE, 'MM-DD')
        OR 
           TO_CHAR(PPS.DATE_START, 'MM-DD') = TO_CHAR(SYSDATE, 'MM-DD')
        )
    AND PPS.DATE_START <> TRUNC(SYSDATE)
ORDER BY 
    HOUFT.NAME,PAPF.PERSON_NUMBER,PPNF.FULL_NAME